version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
  pre_build:
    commands:
      - npm install -g flutter
  build:
    commands:
      - flutter build web
artifacts:
  files:
    - '**/*'
  base-directory: 'build/web'
